services:
  builder:
    build:
      context: .
      dockerfile: docker/Dockerfile.legacy
    volumes:
      - $HOME/tmp-qt6/build:/build:Z
      - ./scripts/build_qt6.sh:/scripts/build_qt6.sh
      - ./toolchain:/src/toolchain
      - ./examples:/src/examples
    privileged: true
  sandbox:
    build: .
    privileged: true
